version: "3" # Compose 파일 버전. v3 이상을 권장합니다.
services: # 여러 서비스(컨테이너)를 정의하는 최상위 키
  db: # 이 서비스의 이름을 "db"라고 붙임
    image: postgres:16 # Docker Hub에서 가져올 이미지 이름과 태그
    container_name: brain-postgres
    restart: always # 컨테이너가 중단되었을 때 자동 재시작 정책
    environment: # 환경변수 목록 (DB 접속 정보 등)
      POSTGRES_USER: postgres # 데이터베이스 유저
      POSTGRES_PASSWORD: postgres # 비밀번호
      POSTGRES_DB: brain_db # 컨테이너 시작 시 자동 생성할 데이터베이스 이름
    ports:
      - "5432:5432" # 호스트(왼쪽) : 컨테이너(오른쪽) 포트 매핑
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
        # 호스트의 ./postgres-data 폴더를
        # 컨테이너 내부의 /var/lib/postgresql/data에 연결해
        # 데이터가 남도록 설정
